#!/bin/sh

# =========================
# Variables
# =========================
DATASTORE_ORIGEN="HDD_datastore1"
DATASTORE_REMOTE="HDD_datastore2"
BASE_VM="RHEL9"
NEW_VM="TEMPLATE_RHEL9"
BASE_VMID=78

# =========================
# 1. Apagar la VM base
# =========================
vim-cmd vmsvc/getallvms
#vim-cmd vmsvc/power.off $BASE_VMID
vim-cmd vmsvc/power $BASE_VMID

# Esperar apagado limpio
sleep 5

# =========================
# 2. Copiar el directorio de la VM base
# =========================
cp -r /vmfs/volumes/$DATASTORE_ORIGEN/$BASE_VM \
      /vmfs/volumes/$DATASTORE_REMOTE/$NEW_VM

# =========================
# 3. Renombrar el archivo .vmx
# =========================
mv /vmfs/volumes/$DATASTORE_REMOTE/$NEW_VM/$BASE_VM.vmx \
   /vmfs/volumes/$DATASTORE_REMOTE/$NEW_VM/$NEW_VM.vmx

# =========================
# 4. Editar el .vmx para cambiar el nombre visible
# =========================


sed -i "s/^displayName = \".*\"/displayName = \"$NEW_VM\"/" /vmfs/volumes/$DATASTORE_REMOTE/$NEW_VM/$NEW_VM.vmx

# =========================
# 5. Limpiar UUID y MAC (EVITA CONFLICTOS)
# =========================
sed -i '/uuid.bios/d' \
       /vmfs/volumes/$DATASTORE_REMOTE/$NEW_VM/$NEW_VM.vmx
sed -i '/uuid.location/d' \
       /vmfs/volumes/$DATASTORE_REMOTE/$NEW_VM/$NEW_VM.vmx
sed -i '/ethernet.*address/d' \
       /vmfs/volumes/$DATASTORE_REMOTE/$NEW_VM/$NEW_VM.vmx

# =========================
# 6. Registrar la nueva VM (pool ROOT = 0)
# =========================
vim-cmd solo/registervm \
/vmfs/volumes/$DATASTORE_REMOTE/$NEW_VM/$NEW_VM.vmx 0
vim-cmd vmsvc/rename 79 TEMPLATE_RHEL9

# =========================
# 7. Mostrar VMID asignado
# =========================
vim-cmd vmsvc/reload 79

vim-cmd vmsvc/getallvms

# =========================
# 8. Encender la nueva VM
# =========================
# Sustituye <VMID_NUEVO> por el ID mostrado arriba
# vim-cmd vmsvc/power.on <VMID_NUEVO>

